--  BANCO DE DADOS
CREATE DATABASE BD_LIVRARIA;

USE BD_LIVRARIA;


--CRIAR A TABELA CLIENTE 

-- TABELA CLIENTE
CREATE TABLE TB_CLIENTE (
 COD_CLI  INT  IDENTITY PRIMARY KEY,
 NOME_CLI VARCHAR(100) NOT NULL,
 EMAIL_CLI VARCHAR(100) NOT NULL, 
 RUA_CLI VARCHAR(100) NOT NULL,
 NUM_CLI VARCHAR(10) NOT NULL,
 COMP_CLI VARCHAR(20) DEFAULT 'X',
 CIDADE_CLI VARCHAR(100) NOT  NULL,
 BAIRRO_CLI VARCHAR(100) NOT NULL,
 ESTADO_CLI CHAR(2) NOT NULL,
 CEP_CLI VARCHAR(10) NOT NULL,
 TEL01_CLI VARCHAR(15) NULL,
 TEL02_CLI VARCHAR(15) NULL
) 


-- TABELA  FISICA
CREATE TABLE TB_FISICA(
  COD_CLI INT NOT NULL UNIQUE,
  RG_CLI VARCHAR(20) NULL,
  CPF_CLI VARCHAR(20) NOT NULL UNIQUE,
  SEXO_CLI CHAR(1) CHECK(SEXO_CLI = 'M' or SEXO_CLI = 'F' ),
  DATA_NASC DATE NOT NULL,
  CONSTRAINT FK_CF FOREIGN KEY(COD_CLI) REFERENCES TB_CLIENTE(COD_CLI)
  ON DELETE CASCADE ON UPDATE CASCADE
  )

-- TABELA JURIDICA
CREATE TABLE TB_JURIDICA(
 COD_CLI INT NOT NULL  UNIQUE, 
 CNPJ_CLI VARCHAR(20) NOT NULL UNIQUE,
 IE_CLI VARCHAR(20) NOT NULL,
 CONSTRAINT FK_CK FOREIGN KEY(COD_CLI) REFERENCES TB_CLIENTE(COD_CLI)
 ON DELETE CASCADE ON UPDATE CASCADE
);



-- TABELA PEDIDO 
 CREATE TABLE TB_PEDIDO(
   N_PED INT PRIMARY KEY IDENTITY,
   COD_CLI INT NOT NULL,
   VALOR_PED DECIMAL(10,2),
   DATA_PED DATETIME ,
   CONSTRAINT TB_PED_CLI FOREIGN KEY(COD_CLI) REFERENCES TB_CLIENTE(COD_CLI) 
   ON DELETE CASCADE ON UPDATE CASCADE
);
 
 
 -- TABELA LIVROS
CREATE TABLE TB_LIVRO(
  COD_LIV INT IDENTITY PRIMARY KEY,
  TITULO_LIV VARCHAR(100) NOT NULL,
  QTPAG_LIV SMALLINT NOT NULL,
  DESC_LIV TEXT, 
  ANOLAC_LIV DATE,
  PRECO_LIV DECIMAL(10,2) NOT NULL,
  ISBN_LIV VARCHAR(20) UNIQUE,
  IMG_LIV VARCHAR(100), 
  QTD_LIV SMALLINT
)

 
-- TABELA DE ITENS_LIVRO TABELA DE RELACIONAMENTO ENTRE LIVRO E PEDIDO
CREATE TABLE TB_ITENS_PED(
  N_PED INT NOT NULL,
  COD_LIV INT NOT NULL,
  QTD_ITEM SMALLINT,
  CONSTRAINT FK_IP_PED FOREIGN KEY(N_PED) 
  REFERENCES TB_PEDIDO(N_PED)ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_IP_LIV FOREIGN KEY(COD_LIV)
  REFERENCES TB_LIVRO(COD_LIV)ON DELETE CASCADE ON UPDATE CASCADE
)


-- TABELA DE AUTOR
CREATE TABLE TB_AUTOR(
 COD_AUT INT  PRIMARY KEY IDENTITY,
 NOME_AUT VARCHAR(100) NOT NULL
);


-- TABELA DE RELACIONAMENTO ENTRE AUTOR / LIVRO
 
 CREATE TABLE TB_AUTO_LIVRO(
    COD_AUT INT,
    COD_LIV INT,  
  CONSTRAINT FK_AL_AUT FOREIGN KEY(COD_AUT) 
  REFERENCES TB_AUTOR(COD_AUT)ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_AL_LIV FOREIGN KEY(COD_LIV)
  REFERENCES TB_LIVRO(COD_LIV)ON DELETE CASCADE ON UPDATE CASCADE
);



 -- TABELA EDITORA
 CREATE TABLE TB_EDITORA(
  COD_ED INT IDENTITY PRIMARY KEY,
  NOME_ED VARCHAR(100)
 );



-- TABELA DE RELACIONAMENTO ENTRE EDITORA E LIVRO
 CREATE TABLE TB_ED_LIV(
 COD_LIV INT ,
 COD_ED INT,
 CONSTRAINT FK_EDLIV_LIV FOREIGN KEY(COD_LIV) 
 REFERENCES TB_LIVRO(COD_LIV) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT FK_EDLIV_ED FOREIGN KEY(COD_ED) 
 REFERENCES TB_EDITORA(COD_ED) ON DELETE CASCADE ON UPDATE CASCADE
 );
 
